### PR TITLE
Eslint root issue fixed + enforce npm, node and yarn versions + fixes all warnings in example

### PR DESCRIPTION
**Pull request by nazariyv**
Would be great to integrate to main to avoid sync issues and to remedy the problems other v3 participants inevitably have

### CODE REVIEW

**Comment by kremalicious** [comment]
hey there, thanks for that! Local development definitely needs improvement.

The example is just that though, an example. So this should not influence the downgrading of root packages for the whole project.

And in general: never mix package managers in one project. Only use one. We use `npm` in all our projects so that will be it. Otherwise we will be forced to do installation/updates of packages with 2 different managers to update their respective lock files. Dependabot will also get confused then.

So I cherry-picked your commit 21ba0185387656bdf6dc2617fa730cbcc34b28c2 and solved the ESLint issue over there in #104

**Comment by kremalicious** [comment]
@nazariyv could you open up a new issue in case there are still issues with example app after recent merges in `main`? Personally, I'm running into weird issues still, don't know if there's have that too

**Comment by nazariyv** [comment]
@kremalicious Hey Matt, will be checking out soon.

**Comment by kremalicious** [comment]
yeah, a lot happened in the last days in this repo too. Most weird issues should be gone

**Comment by nazariyv** [comment]
@kremalicious what I am noticing just now is some problems with the imports in the example directory. I think tsc is getting very confused. I have also modified readme in naz-v3/2: https://github.com/oceanprotocol/react/tree/naz/2 branch to make it clear that that install should be ran in their own repos, not here. For local development, they should run `yarn` or `npm install` otherwise the imports will get weird inside of this repo (there are a bunch of imports @oceanprotocol/react inside of the lib itself, so if you clone and run that install command you will also get the @oceanprotocol/react in your node_modules and rather than importing from local, it will import from node_modules)

Will make a PR later on

**Pull request closed without merging**
